"""create carrier table

Revision ID: d5a02ce8def5
Revises: 
Create Date: 2026-01-12 23:28:10.833838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a02ce8def5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier_code', sa.String(), nullable=False),
    sa.Column('friendly_name', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('requires_funded_amount', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_account_number'), 'carrier', ['account_number'], unique=True)
    op.create_index(op.f('ix_carrier_carrier_code'), 'carrier', ['carrier_code'], unique=False)
    op.create_index(op.f('ix_carrier_id'), 'carrier', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carrier_id'), table_name='carrier')
    op.drop_index(op.f('ix_carrier_carrier_code'), table_name='carrier')
    op.drop_index(op.f('ix_carrier_account_number'), table_name='carrier')
    op.drop_table('carrier')
    # ### end Alembic commands ###
